export enum Events {
    READY = "ready",
    TRACK_ADD = "trackAdd",
    TRACKS_ADD = "tracksAdd",
    TRACK_START = "trackStart",
    TRACK_ERROR = "trackError",
    TRACK_FINISH = "trackEnd",
    QUEUE_END = "queueEnd",
    VOICE_CONNECTION_READY = "voiceReady",
    VOICE_CONNECTION_ERROR = "voiceError",
    VOICE_CONNECTION_DISCONNECT = "voiceDisconnect",
    AUDIO_PLAYER_ERROR = "audioPlayerError",
}
export enum WSOpCodes {
    HELLO = 0,
    VOICE_STATE_UPDATE = 1,
    IDENTIFY = 10,
}

export enum WSEvents {
    READY = "READY",
    TRACK_ADD = "TRACK_ADD",
    TRACKS_ADD = "TRACKS_ADD",
    TRACK_START = "TRACK_START",
    TRACK_FINISH = "TRACK_FINISH",
    TRACK_ERROR = "TRACK_ERROR",
    QUEUE_END = "QUEUE_END",
    QUEUE_STATE_UPDATE = "QUEUE_STATE_UPDATE",
    VOICE_CONNECTION_READY = "VOICE_CONNECTION_READY",
    VOICE_CONNECTION_ERROR = "VOICE_CONNECTION_ERROR",
    VOICE_CONNECTION_DISCONNECT = "VOICE_CONNECTION_DISCONNECT",
    AUDIO_PLAYER_ERROR = "AUDIO_PLAYER_ERROR",
    AUDIO_PLAYER_STATUS = "AUDIO_PLAYER_STATUS",
}
